services:
  postgres-client:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=apartment-slots-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
  postgres-test-client:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=test-apartment-slots-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - '5433:5432'